# Default Compose config: runs GHC with SQLite backend and cronjobs
version: "3"

services:
  geohealthcheck:
    image: geopython/geohealthcheck:latest
    ports:
      - 8083:80
#    environment:
#       GHC_USER_PLUGINS: 'GeoHealthCheck.plugins.user.mywmsprobe,GeoHealthCheck.plugins.user.mywmsprobe2'
    volumes:
      - ghc_sqlitedb:/GeoHealthCheck/DB
      # Optional Plugins, Path on the host, relative to the Compose file
      # See https://docs.docker.com/compose/compose-file/#volumes
      # - ./../GeoHealthCheck/plugins:/plugins:ro

  geohealthcheck-runner:
    image: geopython/geohealthcheck:latest
    depends_on:
      - geohealthcheck

    # Override settings to enable email notifications and user Plugins
#    environment:
#      LC_ALL: "nl_NL.UTF-8"
#      LANG: "nl_NL.UTF-8"
#      LANGUAGE: "nl_NL.UTF-8"
#      GHC_NOTIFICATIONS: 'true'
#      GHC_NOTIFICATIONS_VERBOSITY: 'true'
#      GHC_ADMIN_EMAIL: 'us@gmail.com'
#      GHC_NOTIFICATIONS_EMAIL: 'us@gmail.com,them@domain.com'
#      GHC_SMTP_SERVER: 'smtp.gmail.com'
#      GHC_SMTP_PORT: 587
#      GHC_SMTP_TLS: 'true'
#      GHC_SMTP_SSL: 'false'
#      GHC_SMTP_USERNAME: 'us@gmail.com'
#      GHC_SMTP_PASSWORD: 'the_passw'
#      GHC_USER_PLUGINS: 'GeoHealthCheck.plugins.user.mywmsprobe,GeoHealthCheck.plugins.user.mywmsprobe2'

    entrypoint:
      - bash
      - /run-scheduler.sh

    volumes:
      - ghc_sqlitedb:/GeoHealthCheck/DB
      # Optional Plugins, Path on the host, relative to the Compose file
      # See https://docs.docker.com/compose/compose-file/#volumes
      # - ./../GeoHealthCheck/plugins:/plugins:ro

# docker-compose v2+ needs separate volumes section
volumes:
  ghc_sqlitedb:
